ANS_LIST = {'pilocarpine':['m agonist',['dry eye'],['sweating','lacrimation','diarrhea']],
	'bethanechol':['m agonist',['urinary retention','GI atony'],['sweating','urinary incontinence']],
	'methacholine':['m agonist',['bronchoprovocation'],['salivation','urinary incontinence','diarrhea']],
	'scopolamine':['m antagonist',['motion sickness'],['glaucoma','dry eye']],
	'ipratropium':['m antagonist',['asthma'],['dry mouth','throat irrittion']],
	'atropine':['m antagonist',['organophosphate poisoning','pupil dilation'],['cycloplegia','hallucination']],
	'tropicamide':['m antagonist',['pupil dilation'],['cycloplegia','mydriasis','glaucoma']],
	'succinylcholine':['n agonist',['muscle relaxant'],['myalgia']],
	'varenicline':['n partial agonist',['nicotine addiction'],['suicidal ideation']],
	'tubocurarine':['n antagonist',['muscle relaxant'],['tachycardia','hypotension','bronchoconstriction']],
	'atracurium':['n antagonist',['muscle relaxant'],['seizure']],
	'rocuronium':['n antagonist',['muscle relaxant'],['well tolerated']],
	'rivastigmine':['ChE inhibitor',['alzheimer'],['diarrhea','salivation']],
	'edrophonium':['ChE inhibitor',['MG','atropine poisoning'],['diarrhea','urinary incontinence']],
	'pyridostigmine':['ChE inhibitor',['MG','atropine poisoning'],['sweating','salivation','urinary incontinence']],
	'neostigmine':['ChE inhibitor',['MG','NMJ blocker'],['diarrhea','salivation','urinary incontinence']],
	'physostigmine':['ChE inhibitor',['atropine poisoning'],['salivation']],
	'donepezil':['ChE inhibitor',['alzheimer'],['salivation']],
	'phenylephrine':['a1 agonist',['pupil dilation','hypertension','decongestion'],['bradycardia','urinary retention']],
	'doxazosin':['a1 antagonist',['prostatic','hypertension','urinary retention'],['nasal congestion','tachycardia']],
	'prazosin':['a1 antagonist',['urinary retention','prostatic'],['tachycardia']],
	'tamsulosin':['a1 antagonist',['urinary retention','prostatic','hypertension'],['orthostatic hypotension','nasal congestion']],
	'phenoxybenzamine':['nonse a antagonist',['pheochromocytoma','hypertension'],['orthostatic hypotension','arrhythmia','tachycardia']],
	'phentolamine':['nonse a antagonist',['hypertension'],['palpitation']],
	'brimonidine':['a2 agonist',['glaucoma'],['eye irritation']],
	'clonidine':['a2 agonist',['opioide withdraw'],['hypertension']],
	'yohimbine':['a2 antagonist',['erectile dysfunction'],['priapism']],
	'dobutamine':['b1 agonist',['cardiogenic shock'],['palpitation','tachycardia']],
	'soproterenol':['nonse b agonist',['increased heart contractility'],['tachycardia','palpitation']],
	'atenolol':['b1 antagonist',['coronary artery disease'],['hypotension','bradycardia','raynaud syndrome']],
	'metoprolol':['b1 antagonist',['hypertension','coronary artery disease'],['erectile dysfunction','diarrhea','fatigue']],
	'salbutamol':['b2 agonist',['asthma'],['hypotension']],
	'formeterol':['b2 agonist',['asthma'],['tremor','tachycardia']],
	'salmeterol':['b2 agonist',['asthma'],['tremor','tachycardia']],
	'terbutaline':['b2 agonist',['asthma','uterine relaxation','premature labor'],['tremor','hyperglycemia','tachycardia']],
	'albuterol':['b2 agonist',['asthma'],['hyperglycemia','palpitation']],
	'ritodrine':['b2 agonist',['uterine relaxation','premature labor'],['tachycardia','hyperglycemia','tremor']],
	'pindolol':['nonse b antagonist',['hypertension','arrthythmia','angina'],['heart block','bradycardia']],
	'propranolol':['nonse b antagonist',['coronary artery disease'],['erectile dysfunction']],
	'timolol':['nonse b antagonist',['glaucoma'],['asthma']],
	'norepinephrine':['ab agonist',['increased heart contractility'],['asthma','arrhythmia']],
	'dopamine':['ab agonist',['vasoconstriction','septic shock'],['palpitation','tachycardia']],
	'epinephrine':['ab agonist',['anaphylaxis'],['palpitation']],
	'pseudoepedrine':['ab agonist',['decongestion'],['tachycardia','palpitation','tremor']],
	'carvedilol':['ab antagonist',['coronary artery disease','angina'],['bradycardia','erectile dysfunction','heart block']],
	'labetalol':['ab antagonist',['hypertension'],['raynaud syndrome']]}

GI_LIST = {'bethanechol':['m agonist',['urinary retention','GI atony'],['diarrhea','urinary incontinence','bronchoconstriction','salivation','sweating']],
	'propranolol':['nonse b antagonist',['esophageal varices'],['bradycardia','heart block','hypotension','bronchoconstriction','asthma','coronary vasospasm','raynaud syndrome','fatigue','erectile dysfunction','mask hypoglycemia']],
	'omeprazole':['proton pump inhibitor',['peptic ulcer','GI reflux'],['hypergastrinemia','anemia','osteoporosis','tetany','drug interaction']],
	'cimetidine':['h2 antagonist',['peptic ulcer','GI reflux'],['drug interaction']],
	'ranitidine':['h2 antagonist',['peptic ulcer','GI reflux'],['well tolerated']],
	'famotidine':['h2 antagonist',['peptic ulcer','GI reflux'],['well tolerated']],
	'aluminium hydroxide':['antacid',['peptic ulcer','GI reflux'],['drug interaction','constipation']],
	'magnesium hydroxide':['antacid',['peptic ulcer','GI reflux','constipation'],['drug interaction','diarrhea']],
	'alum milk':['antacid',['peptic ulcer','GI reflux'],['drug interaction']],
	'calcium carbonate':['antacid',['peptic ulcer','GI reflux'],['drug interaction','constipation','belching']],
	'sodium bicarbonate':['antacid',['peptic ulcer','GI reflux'],['belching']],
	'misoprostol':['PGE analog',['peptic ulcer'],['diarrhea','uterine contraction']],
	'sucralfate':['coat ulcer',['peptic ulcer'],['well tolerated']],
	'metoclopramide':['d antagonist',['N/V','GI reflux','gastroparesis'],['arrhythmia','hyperprolactinemia','extrapyramidal','dystonia']],
	'domperidone':['d antagonist',['N/V','GI reflux','gastroparesis'],['arrhythmia','hyperprolactinemia']],
	'cisapride':['5-HT4 agonist',['GI reflux','gastroparesis'],['arrhythmia']],
	'ondansetron':['5-HT3 antagonist',['N/V'],['constipation']],
	'simethicone':['surfactant',['flatulence'],['well tolerated']],
	'loperamide':['opioid agonist',['diarrhea'],['constipation','systemic infection','toxic megacolon']],
	'psyllium':['bulk forming',['constipation'],['belching']],
	'isphagula husk':['bulk forming',['constipation'],['belching']],
	'methylcellulose':['bulk forming',['constipation'],['belching']],
	'milk of megnesia':['osmotic',['constipation'],['diarrhea']],
	'lactulose':['osmotic',['constipation','hepatic encephalopathy'],['diarrhea']],
	'docusate':['stool softener',['constipation'],['well tolerated']],
	'bisacodyl':['irritant',['constipation'],['abdominal spasm']],
	'activated charcoal':['adsorption',['diarrhea'],['drug interaction']],
	'butylscopolamine':['m antagonist',['abdominal spasm','menstrual cramp'],['constipation','urinary retention','dry mouth','dry eye']],
	'hyoscine butylbromide':['m antagonist',['abdominal spasm','menstrual cramp'],['constipation','urinary retention','dry mouth','dry eye']]}

MGI_LIST = {'bethanechol':['m agonist',['urinary retention','GI atony'],['diarrhea','urinary incontinence','bronchoconstriction','salivation','sweating']],
	'omeprazole':['proton pump inhibitor',['peptic ulcer','GI reflux'],['hypergastrinemia','anemia','osteoporosis','tetany','drug interaction']],
	'cimetidine':['h2 antagonist',['peptic ulcer','GI reflux'],['drug interaction']],
	'ranitidine':['h2 antagonist',['peptic ulcer','GI reflux'],['well tolerated']],
	'famotidine':['h2 antagonist',['peptic ulcer','GI reflux'],['well tolerated']],
	'aluminium hydroxide':['antacid',['peptic ulcer','GI reflux'],['drug interaction','constipation']],
	'magnesium hydroxide':['antacid',['peptic ulcer','GI reflux','constipation'],['drug interaction','diarrhea']],
	'alum milk':['antacid',['peptic ulcer','GI reflux'],['drug interaction']],
	'calcium carbonate':['antacid',['peptic ulcer','GI reflux'],['drug interaction','constipation','belching']],
	'sodium bicarbonate':['antacid',['peptic ulcer','GI reflux'],['belching']],
	'misoprostol':['PGE analog',['peptic ulcer'],['diarrhea','uterine contraction']],
	'sucralfate':['coat ulcer',['peptic ulcer'],['well tolerated']],
	'metoclopramide':['d antagonist',['N/V','GI reflux','gastroparesis'],['arrhythmia','hyperprolactinemia','extrapyramidal','dystonia']],
	'domperidone':['d antagonist',['N/V','GI reflux','gastroparesis'],['arrhythmia','hyperprolactinemia']],
	'cisapride':['5-HT4 agonist',['GI reflux','gastroparesis'],['arrhythmia']],
	'ondansetron':['5-HT3 antagonist',['N/V'],['constipation']],
	'loperamide':['opioid agonist',['diarrhea'],['constipation','systemic infection','toxic megacolon']],
	'psyllium':['bulk forming',['constipation'],['belching']],
	'isphagula husk':['bulk forming',['constipation'],['belching']],
	'methylcellulose':['bulk forming',['constipation'],['belching']],
	'milk of megnesia':['osmotic',['constipation'],['diarrhea']],
	'lactulose':['osmotic',['constipation','hepatic encephalopathy'],['diarrhea']],
	'docusate':['stool softener',['constipation'],['well tolerated']],
	'bisacodyl':['irritant',['constipation'],['abdominal spasm']],
	'activated charcoal':['adsorption',['diarrhea'],['drug interaction']]}